/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useRef } from "react";
import { useScroll, useTransform, motion } from "motion/react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

type AboutTextFillProps = {
  tag?: string;
  title: string;
  description?: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const AboutInline = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  return (
    <div className="relative bg-[#0d0d0d] text-[#faf8f5] py-24 md:py-32 border-t border-b border-[#222222] overflow-hidden">
      {/* Decorative ambient lighting */}
      <div className="absolute top-1/2 left-1/4 -translate-y-1/2 w-[500px] h-[500px] bg-[#c9a96e]/5 rounded-full blur-[120px] pointer-events-none" />

      <div className="w-content-width mx-auto px-4 md:px-8 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-center">
          
          {/* Sol Taraf: Hakan Ertunç Dikey Fotoğraf Alanı */}
          <motion.div 
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, ease: "easeOut" }}
            className="lg:col-span-5 relative"
          >
            <div className="relative aspect-[3/4] w-full overflow-hidden rounded-sm bg-[#161616] border border-[#2a241a] shadow-2xl group">
              <img
                src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=1000"
                alt="Hakan Ertunç"
                className="w-full h-full object-cover object-top filter grayscale contrast-105 group-hover:grayscale-0 transition-all duration-700 opacity-90 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-[#0d0d0d] via-transparent to-transparent opacity-80" />
              
              {/* Bej Rozet Detayı */}
              <div className="absolute bottom-6 left-6 right-6 p-5 border border-[#c9a96e]/30 bg-[#0d0d0d]/90 backdrop-blur-md rounded-sm">
                <span className="text-[11px] uppercase tracking-[0.25em] text-[#c9a96e] font-medium block">
                  Private Advisory
                </span>
                <span className="text-xs font-light text-[#e0d8c8] mt-1 block tracking-wider">
                  Real Estate &amp; Mega Yachts
                </span>
              </div>
            </div>
          </motion.div>

          {/* Sağ Taraf: Başlık, Alt Başlık ve Tanıtım Metni */}
          <motion.div 
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.15, ease: "easeOut" }}
            className="lg:col-span-7 flex flex-col justify-center"
          >
            <div className="inline-flex items-center gap-3 mb-4">
              <span className="h-[1px] w-10 bg-[#c9a96e]" />
              <span className="text-xs uppercase tracking-[0.3em] text-[#c9a96e] font-medium">
                About Hakan Ertunç
              </span>
            </div>

            <h2 className="text-4xl md:text-5xl lg:text-6xl font-serif font-light tracking-tight text-[#faf8f5] mb-2 uppercase">
              HAKAN ERTUNÇ
            </h2>

            <p className="text-base md:text-lg text-[#c9a96e] uppercase tracking-[0.22em] font-light mb-8">
              Private Real Estate &amp; Yachts
            </p>

            <div className="space-y-5 text-[#d0c9bd] font-light text-base md:text-lg leading-relaxed border-l-2 border-[#c9a96e]/40 pl-6 my-2">
              <p>
                Dünyanın en seçkin destinasyonlarında ultra lüks gayrimenkul ve portföy dışı mega yat yönetimi konusunda uzmanlaşmış özel danışmanlık hizmeti.
              </p>
              <p>
                Ayrıcalıklı müşterilerimize maksimum gizlilik, küresel pazar erişimi ve terzi usulü çözümler sunarak benzersiz bir yaşam tarzı ve yatırım deneyimi sağlıyoruz.
              </p>
            </div>

            {/* İstatistik / Detay Özet Bilgileri */}
            <div className="grid grid-cols-3 gap-6 pt-10 mt-8 border-t border-[#222222]">
              <div>
                <span className="text-2xl md:text-3xl font-serif font-light text-[#c9a96e] block">
                  15+
                </span>
                <span className="text-[11px] uppercase tracking-widest text-[#a0988a] mt-1 block">
                  Yıllık Deneyim
                </span>
              </div>
              <div>
                <span className="text-2xl md:text-3xl font-serif font-light text-[#c9a96e] block">
                  €500M+
                </span>
                <span className="text-[11px] uppercase tracking-widest text-[#a0988a] mt-1 block">
                  Portföy Hacmi
                </span>
              </div>
              <div>
                <span className="text-2xl md:text-3xl font-serif font-light text-[#c9a96e] block">
                  100%
                </span>
                <span className="text-[11px] uppercase tracking-widest text-[#a0988a] mt-1 block">
                  Gizlilik
                </span>
              </div>
            </div>
          </motion.div>

        </div>
      </div>
    </div>
  );
};

export default function AboutSection() {
  return (
    <div data-webild-section="about" data-section="about" id="about">
      <AboutInline />
    </div>
  );
}
