// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextFill from "@/components/sections/about/AboutTextFill";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <AboutTextFill
                textAnimation="fade"
                title="For those who travel like it's an art form."
                imageSrc="https://storage.googleapis.com/webild/default/templates/marbella/about/statement.webp"
              />
            </div>
  );
}
