// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroVideoScroll from "@/components/sections/hero/HeroVideoScroll";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroVideoScroll
                textAnimation="fade"
                videoSrc="https://storage.googleapis.com/webild/default/templates/marbella/hero/hero.mp4"
                tag="Le Cercle Premium Real Estate"
                title="HAKAN ERTUNÇ"
                description="Exclusive beachfront villas and luxury apartments on the Costa del Sol. Your Mediterranean dream, delivered turnkey."
                primaryButton={{ text: "CONTACT ON WHATSAPP", href: "https://wa.me/905376309179?text=Merhaba%20Hakan%20Bey%2C%20gayrimenkul%20ve%20yat%20portf%C3%B6y%C3%BCn%C3%BCz%20hakk%C4%B1nda%20bilgi%20almak%20istiyorum." }}
                secondaryButton={{ text: "İNSTAGRAM", href: "https://www.instagram.com/hakanertunc7/" }}
                bottomText="A premium real estate brand designed for those seeking a refined way of living on the Costa del Sol"
              />
            </div>
  );
}
