// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroVideoScroll from "@/components/sections/hero/HeroVideoScroll";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroVideoScroll
                textAnimation="fade"
                videoSrc="https://storage.googleapis.com/webild/default/templates/marbella/hero/hero.mp4"
                tag="Le Cercle Premium Real Estate"
                title="Live Where the Sun Meets the Sea"
                description="Exclusive beachfront villas and luxury apartments on the Costa del Sol. Your Mediterranean dream, delivered turnkey."
                primaryButton={{ text: "View Properties", href: "#properties" }}
                secondaryButton={{ text: "Book a Tour", href: "#contact" }}
                bottomText="A premium real estate brand designed for those seeking a refined way of living on the Costa del Sol"
              />
            </div>
  );
}
