/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";

const items = [
  {
    title: "",
    description: "Apartments for sale in a Bosphorus-view residence with a helipad in Istanbul",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3IuuM7YWxcNbyvExWj6VfdRg3Lb/uploaded-1790847503708-182kwcrg.jpg",
    images: [
      "https://storage.googleapis.com/webild/users/user_3IuuM7YWxcNbyvExWj6VfdRg3Lb/uploaded-1790847503708-182kwcrg.jpg",
      "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-1.webp",
      "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-2.webp"
    ]
  },
  {
    title: "Casa del Sol",
    description: "Contemporary beachfront living with floor-to-ceiling glass, rooftop lounge, and direct beach access.",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3IuuM7YWxcNbyvExWj6VfdRg3Lb/uploaded-1788714937082-37vwbxua.webp"
  },
  {
    title: "Villa Andalucía",
    description: "Traditional charm meets modern luxury — courtyard, olive grove, and a heated outdoor pool.",
    imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-3.webp?_wi=1"
  },
  {
    title: "The Meridian",
    description: "Sleek 4-bedroom penthouse villa with smart home technology and sweeping coastal views.",
    imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-4.webp"
  },
  {
    title: "Villa Blanca",
    description: "Minimalist white-washed estate with private cinema, spa suite, and landscaped Mediterranean gardens.",
    imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-5.webp"
  },
  {
    title: "Casa Dorada",
    description: "Golden-hour perfection — west-facing terraces, wine cellar, and an open-plan chef's kitchen.",
    imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-6.webp"
  }
];

type FeatureItem = {
  title: string;
  description: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

type FeaturesMediaColumnsProps = {
  tag?: string;
  title: string;
  description?: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: FeatureItem[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
};

const PropertiesInline = () => {
  return (
    <section aria-label="Features section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          {"Properties" && (
            <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
              <p>{"Properties"}</p>
            </div>
          )}

          <TextAnimation
            text={"Our Villas"}
            variant={"fade"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          {"Handpicked residences in Marbella's most coveted locations, each designed for effortless Mediterranean living." && (
            <TextAnimation
              text={"Handpicked residences in Marbella's most coveted locations, each designed for effortless Mediterranean living."}
              variant={"fade"}
              gradientText={false}
              tag="p"
              className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
            />
          )}

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="slide-up">
          <div className="w-content-width mx-auto grid grid-cols-1 md:grid-cols-2 gap-5">
            {items.map((item) => (
              <div key={item.title} className="flex flex-col gap-3 xl:gap-3.5 2xl:gap-4 h-full">
                <div className="aspect-square rounded overflow-hidden button-secondary shadow shadow-foreground/5">
                  <ImageOrVideo imageSrc={item.imageSrc} videoSrc={item.videoSrc} />
                </div>
                <div className="flex flex-col gap-1">
                  <h3 className="text-3xl font-semibold leading-snug">{item.title}</h3>
                  <p className="text-base leading-snug">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function PropertiesSection() {
  return (
    <div data-webild-section="properties" data-section="properties" id="properties">
      <PropertiesInline />
    </div>
  );
}
