// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "properties" section.

import React from 'react';
import FeaturesMediaColumns from "@/components/sections/features/FeaturesMediaColumns";

export default function PropertiesSection(): React.JSX.Element {
  return (
    <div id="properties" data-section="properties">
              <FeaturesMediaColumns
                textAnimation="fade"
                tag="Properties"
                title="Our Villas"
                description="Handpicked residences in Marbella's most coveted locations, each designed for effortless Mediterranean living."
                items={[
                  { title: "Villa Serena", description: "A sunlit 5-bedroom retreat with infinity pool, panoramic sea views, and private garden terraces.", imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-1.webp" },
                  { title: "Casa del Sol", description: "Contemporary beachfront living with floor-to-ceiling glass, rooftop lounge, and direct beach access.", imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-2.webp" },
                  { title: "Villa Andalucía", description: "Traditional charm meets modern luxury — courtyard, olive grove, and a heated outdoor pool.", imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-3.webp" },
                  { title: "The Meridian", description: "Sleek 4-bedroom penthouse villa with smart home technology and sweeping coastal views.", imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-4.webp" },
                  { title: "Villa Blanca", description: "Minimalist white-washed estate with private cinema, spa suite, and landscaped Mediterranean gardens.", imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-5.webp" },
                  { title: "Casa Dorada", description: "Golden-hour perfection — west-facing terraces, wine cellar, and an open-plan chef's kitchen.", imageSrc: "https://storage.googleapis.com/webild/default/templates/marbella/properties/villa-6.webp" },
                ]}
              />
            </div>
  );
}
